# #####################################################################
# Automatically generated by qmake (2.01a) Mon Nov 17 15:28:53 2008
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += config.h \
    main.h \
    network.h \
    Window.h \
    controller.h
SOURCES += config.cpp \
    main.cpp \
    Window.cpp \
    controller.cpp
QT += opengl \
    network
