######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 17 15:28:53 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += config.h main.h network.h view.h Window.h
SOURCES += config.cpp main.cpp view.cpp Window.cpp
QT += opengl \
network
