######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 8 15:10:22 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += config.h main.h view.h Window.h
SOURCES += config.cpp main.cpp view.cpp Window.cpp
